import fs from 'node:fs';
import path from 'node:path';
import { buildProject } from '../lib/build.js';
import { deployProject, resolveComMojang } from '../lib/deploy.js';
import { CliError } from '../lib/errors.js';
import { lintProject } from '../lib/lint.js';
import { syncManifests } from '../lib/manifest.js';
import { loadProject } from '../lib/project.js';
import { c, elapsed, log, plural, timestamp } from '../lib/term.js';
import { deployOptions } from './deploy.js';

export default {
  name: 'watch',
  aliases: ['dev'],
  group: 'Build & ship',
  summary: 'Re-deploy (or rebuild) automatically whenever a pack file changes',
  usage: 'mcpackage watch [options]',
  description: `Watches the pack folders and mcpackage.json. On every change it lints the
project and, if there are no errors, deploys to Minecraft's development
folders (default) or rebuilds the archives (--build). Press Ctrl+C to stop.`,
  options: {
    ...deployOptions,
    build: { type: 'boolean', short: 'b', description: 'Rebuild dist/ artifacts instead of deploying' },
    debounce: { type: 'string', description: 'Milliseconds to wait after the last change', value: '<ms>', default: '300' },
    'skip-lint': { type: 'boolean', description: 'Deploy even when lint reports errors' },
  },
  examples: ['mcpackage watch', 'mcpackage watch --preview', 'mcpackage watch --build'],
  async run({ options, cwd }) {
    const project = await loadProject(cwd);
    const debounceMs = Number(options.debounce);
    if (!Number.isFinite(debounceMs) || debounceMs < 0) throw new CliError('--debounce must be a number of milliseconds.', { exitCode: 2 });

    let comMojang = null;
    if (!options.build) {
      comMojang = (await resolveComMojang({ explicit: options.target, preview: options.preview })).path;
    }

    // manifest.json is regenerated by the sync step of every cycle, so changes to
    // it must not trigger another cycle (that would loop forever).
    const ignored = /(^|[\\/])(\.git|node_modules|dist)([\\/]|$)|(^|[\\/])manifest\.json$|\.(mcaddon|mcpack|swp|tmp)$|~$/;
    let timer = null;
    let running = false;
    let queued = false;

    const cycle = async (reason) => {
      if (running) {
        queued = true;
        return;
      }
      running = true;
      const started = Date.now();
      try {
        const fresh = await loadProject(project.root);
        await syncManifests(fresh);
        if (!options['skip-lint']) {
          const result = await lintProject(fresh);
          for (const d of result.diagnostics) {
            if (d.level === 'error') log.error(`${c.dim(d.file)} ${d.message}`);
          }
          if (!result.ok) {
            log.warn(`${c.dim(timestamp())} ${plural(result.errors.length, 'error')} — waiting for changes`);
            return;
          }
        }
        if (options.build) {
          const artifacts = await buildProject(fresh, { type: 'addon' });
          log.ok(`${c.dim(timestamp())} built ${artifacts.map((a) => c.cyan(fresh.relative(a.file))).join(', ')} ${c.dim(`(${reason}, ${elapsed(started)})`)}`);
        } else {
          const results = await deployProject(fresh, { comMojang, clean: !options['no-clean'] });
          log.ok(`${c.dim(timestamp())} deployed ${results.map((r) => r.kind).join(' + ')} ${c.dim(`(${reason}, ${elapsed(started)})`)}`);
        }
      } catch (err) {
        log.error(`${c.dim(timestamp())} ${err instanceof CliError ? err.message : err.stack || err.message}`);
      } finally {
        running = false;
        if (queued) {
          queued = false;
          schedule('queued change');
        }
      }
    };

    const schedule = (reason) => {
      clearTimeout(timer);
      timer = setTimeout(() => cycle(reason), debounceMs);
    };

    const watchers = [];
    const watchDirs = [];
    for (const pack of await project.existingPacks()) watchDirs.push(pack.dir);
    if (watchDirs.length === 0) {
      throw new CliError('Nothing to watch: no pack folders exist.', { hint: 'Run `mcpackage add pack behavior` first.' });
    }
    for (const dir of watchDirs) {
      watchers.push(
        fs.watch(dir, { recursive: true }, (_event, filename) => {
          const name = filename ? String(filename) : '';
          if (ignored.test(name)) return;
          schedule(`${project.relative(dir)}/${name.split(path.sep).join('/')}`);
        }),
      );
    }
    watchers.push(
      fs.watch(project.configFile, () => schedule(path.basename(project.configFile))),
    );

    log.print(`${c.bold('mcpackage watch')} ${c.dim(options.build ? 'building on change' : `deploying to ${comMojang}`)}`);
    for (const dir of watchDirs) log.item(`watching ${c.cyan(project.relative(dir))}/`);
    log.item(`watching ${c.cyan(project.relative(project.configFile))}`);
    log.print(c.dim('Press Ctrl+C to stop.'));
    log.blank();

    await cycle('initial');

    await new Promise((resolve) => {
      const stop = () => {
        for (const watcher of watchers) watcher.close();
        clearTimeout(timer);
        log.blank();
        log.info('Watcher stopped.');
        resolve();
      };
      process.once('SIGINT', stop);
      process.once('SIGTERM', stop);
    });
  },
};
